version: '3'

services:
  cake:
    image: theiwaz/cakephp2x:latest
    ports:
      - "8080:80"
    volumes: 
        - ./wwwroot:/var/www/html
    depends_on:
      - mysql
      - mail
  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=SomeAwesomelyDifficultPassword
    volumes: 
      - mysql-cake:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8081:80
    environment:
      - MYSQL_ROOT_PASSWORD=SomeAwesomelyDifficultPassword
      - PMA_HOST=mysql
    depends_on: 
      - mysql
  mail:
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 1025:25
volumes:
  mysql-cake:


